section color No-HEX
MEvgeniy21/team-project-test pull request #3
Opened 2022-03-31 18:41 UTC by YevhenVyn

ця гілка містить помилку. поверни її на баг-фіксинг

2022-03-31 18:51 UTC, MEvgeniy21 requested changes

2022-03-31 18:51 UTC, MEvgeniy21 commented on src/sass/_common.scss
> +  color: pink;}
Шо то тут есть :)

2022-04-01 07:49 UTC, YevhenVyn commented on src/sass/_common.scss
> +  color: pink;}
подправил

2022-04-01 13:34 UTC, MEvgeniy21 approved these changes

2022-04-01 13:35 UTC, merged